#!/usr/bin/env python3
"""generate the additive Material Symbols font and its available icon constants."""

import argparse
from pathlib import Path

from fontTools import subset
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("font", type=Path)
parser.add_argument("codepoints", type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parent
legacy = TTFont(root / "MaterialIcons-Regular.ttf").getBestCmap()
font = TTFont(args.font, recalcTimestamp=False)
available = font.getBestCmap()
icons = []
for line in args.codepoints.read_text().splitlines():
    name, value = line.split()
    code = int(value, 16)
    # cimgui-go uses 16-bit ImWchar; preserve every existing private-use glyph.
    if 0xE000 <= code <= 0xF8FF and code not in legacy and code in available:
        icons.append((name, code))

instantiateVariableFont(font, {"FILL": 1, "GRAD": 0, "opsz": 24, "wght": 400}, inplace=True)

# ImGui sizes fonts by ascent minus descent. use the square em metrics of Material Icons so the
# supplement's extra line leading does not shrink its icon cells or shift their baselines.
em = font["head"].unitsPerEm
font["hhea"].ascent, font["hhea"].descent, font["hhea"].lineGap = em, 0, 0
font["OS/2"].sTypoAscender, font["OS/2"].sTypoDescender, font["OS/2"].sTypoLineGap = em, 0, 0
font["OS/2"].usWinAscent, font["OS/2"].usWinDescent = em, 0

# the real-size lettering occupies only about half the em width. enlarge it optically while keeping
# its square advance, so it reads alongside the fit icon without changing button padding or layout.
name = available[0xF4C2]
glyph = font["glyf"][name]
glyph.recalcBounds(font["glyf"])
scale = 1.5
dx = em / 2 - (glyph.xMin + glyph.xMax) / 2 * scale
dy = em / 2 - (glyph.yMin + glyph.yMax) / 2 * scale
glyphs = font.getGlyphSet()
pen = TTGlyphPen(glyphs)
glyphs[name].draw(TransformPen(pen, (scale, 0, 0, scale, dx, dy)))
font["glyf"][name] = pen.glyph()
font["glyf"][name].recalcBounds(font["glyf"])
font["hmtx"][name] = (em, font["glyf"][name].xMin)

options = subset.Options()
options.recalc_timestamp = False
options.layout_features = []
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes={code for _, code in icons})
subsetter.subset(font)
font.save(root / "MaterialSymbolsSupplement.ttf")
lines = ["// code generated by generateMaterialSymbols.py; DO NOT EDIT.", "", "package fonts", ""]
lines += [f"const ICON_SYMBOL_{name.upper()} = string('\\u{code:04x}')" for name, code in icons]
(root / "materialSymbols.go").write_text("\n".join(lines) + "\n")
print(f"generated {len(icons)} symbols ({len({code for _, code in icons})} unique codepoints)")
